#
# Copyright (c) 2005 by Naohide Sano, All rights reserved.
#
# Properties File for vavi.sound.smaf
#
# 0.00 050506 nsano initial version
#

VN=Vender Name,true
CN=Carrier Name,true
CA=Category Name,true
ST=Song Name,true
AN=Artist Name,true
WW=Lyrics,true
SW=Composer,true
AW=Arranger,true
CR=Copyright(c),true
GR=Management Group,true
MI=Managed Information,true
CD=Created Date,true
UD=Updated Date,true
ES=Edited Status,false
VC=vCard,true
IC=Image Creator,false
IR=Image Rights,false
IP=Image Producer,false
TR=Text Rights,true
TP=Text Producer,true
GP=Total Producer,true
VE=Reserved,false
CE=Reserved,false
UI=Reserved,false
OW=Reserved,false
A0=Reserved,true
A1=Reserved,true
A2=Reserved,true
