vavi.sound.smaf.Sequencer=vavi.sound.smaf.vavi.VaviSmafSequencer
vavi.sound.smaf.Synthesizer=vavi.sound.smaf.vavi.VaviSmafSynthesizer
vavi.sound.smaf.spi.MidiConverter=vavi.sound.smaf.vavi.VaviSmafMidiConverter
