#
# Copyright (c) 2005 by KLab Inc., All rights reserved.
#
# Written by Naohide Sano
#
# properties for MfiWithVoiceMaker
#
# @author Naohide Sano
# @version 0.00 050402 nsano initial version
#

##
# Author information
#
prot=vavi

##
#
#
sorc=0

##
#
#
vers=0300

##
#
#
defaultModel=sh900

##
