vavi.sound.mfi.Sequencer=vavi.sound.mfi.vavi.VaviMfiSequencer
vavi.sound.mfi.Synthesizer=vavi.sound.mfi.vavi.VaviMfiSynthesizer
vavi.sound.mfi.spi.MidiConverter=vavi.sound.mfi.vavi.VaviMfiMidiConverter
